// <auto-generated />
using System;
using Desafio.Credito.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio.Credito.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325231800_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Desafio.Credito.Infrastructure.Data.Entities.EvolucaoContrato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amortizacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataProcessamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<decimal>("JurosPeriodo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Prestacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoAposPagar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EvolucaoContrato", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
